### ISSUE TITLE
Module settings jump back to the top when opening a category

### ISSUE THREAD

**Issue by GreenThreat** [illandril/FoundryVTT-tidy-module-settings#3]
Scroll down, open one of the collapsed modules and the scroll bar will reset to the top, forcing you to scroll down to where you just opened it

**Comment by illandril** [comment]
I cannot reproduce this issue. If I expand or collapse a module, my Settings window stays scrolled exactly where it was.

What browser are you using, and what other modules do you have enabled when you see this?

**Comment by GreenThreat** [comment]
I did some further investigation. The issues is not dependent on the browser, instead it's a compatibility issue with the module "Ernie's Modern UI".
