### ISSUE TITLE
Cannot collapse settings

### ISSUE THREAD

**Issue by GreenThreat** [illandril/FoundryVTT-tidy-module-settings#4]
All module settings are permanently expanded. The "+" and "-" signs do not work. No UI overhaul is active, deactivating and reactivating the module does not fix it
Preview:
![image](https://user-images.githubusercontent.com/37253193/125208060-96512380-e290-11eb-91fa-f4671c3da459.png)

**Comment by illandril** [comment]
What other modules do you have active (including version)?

What system are you using (including version)?

What version of FoundryVTT?

What browser (including version)?

**Comment by GreenThreat** [comment]
Found the culprit, sorry, I should really do some investigation beforehand.
Compatibility issue with the module [Socket Settings by Blitz](https://github.com/BlitzKraig/fvtt-SocketSettings)
Version is 0.05.
